### ISSUE TITLE
Broken link on Teaching Resources 

### ISSUE THREAD

**Issue by SteveMarvin** [hyperstudio/cfrp-website#9]
On https://www.cfregisters.org/en/teaching-resources, the link to Pedagogical Exercises Using Database Visualizatrions Drawn from the Comédie-Française Registers Project."  (In French) is broken.

**Comment by circa1977** [comment]
These are editable in the content management system and should be raised to @jsravel4 or Sara.

**Comment by SteveMarvin** [comment]
I am a tester for Performant Software, tasked by Jamie with going over the website and creating issues for broken links, errors, missing images, "insecure" pages, where the browser reports that not all resources on the page were loaded securely, etc. 

I have five repositories I've been given to place the issues I find, but I will just not have time to track down the appropriate recipient or assignee for every issue. In addition, I don't have permissions to attach labels or assignments on this repo. Please let me know if this methodology is unworkable, or needs to be revised.

**Comment by jsravel4** [comment]
Jamie, would you please weigh in on this question?

Thanks,
Jeff

******************************************
Jeffrey S. Ravel
Professor and Head of History
MIT History Faculty, E51-255
77 Massachusetts Avenue
Cambridge, MA 02139

tel:  617.253.4451
fax: 617.253.9406
ravel@mit.edu<mailto:ravel@mit.edu>
http://history.mit.edu/people/jeffrey-s-ravel
******************************************



On Aug 28, 2018, at 1:19 PM, SteveMarvin <notifications@github.com<mailto:notifications@github.com>> wrote:


I am a tester for Performant Software, tasked by Jamie with going over the website and creating issues for broken links, errors, missing images, "insecure" pages, where the browser reports that not all resources on the page were loaded securely, etc.

I have five repositories I've been given to place the issues I find, but I will just not have time to track down the appropriate recipient or assignee for every issue. In addition, I don't have permissions to attach labels or assignments on this repo. Please let me know if this methodology is unworkable, or needs to be revised.

**Comment by SteveMarvin** [comment]
@jsravel4 Do you want me to suspend testing in the meantime?

**Comment by jsravel4** [comment]
Dear All,

This is supposed to be five hours of testing by a Performant employee to see if links are working properly on cfrgeisters.org<http://cfrgeisters.org>.  At the end of the five hours, I had anticipated getting a report from the tester.  I did not anticipate receiving several e-mails in my in-box while the testing was in progress.

I would recommend halting this procedure until Performant figures out the proper protocol, and can provide a summary at the end of the testing.

Thanks,
Jeff

******************************************
Jeffrey S. Ravel
Professor and Head of History
MIT History Faculty, E51-255
77 Massachusetts Avenue
Cambridge, MA 02139

tel:  617.253.4451
fax: 617.253.9406
ravel@mit.edu<mailto:ravel@mit.edu>
http://history.mit.edu/people/jeffrey-s-ravel
******************************************



On Aug 28, 2018, at 1:24 PM, Mark Reeves <notifications@github.com<mailto:notifications@github.com>> wrote:


@jamiefolsom<https://github.com/jamiefolsom> I'm seeing tickets appear in my inbox as a watcher and am happy to fix template-level links for the Craft website. Are you planning on sweeping these for assignment otherwise, though? Or is this a queue you had another plan for? I was able to deduce Jeff's handle...I'm not sure of Sara's, and content-level links can be edited by them in the CMS.

**Comment by jamiefolsom** [comment]
Hi @circa1977 and @jsravel4 -- yes, I will vet these issues, and those created on all other CFRP repos, and assign to the appropriate person. Mark, if you have hours allocated to the Craft site, it would be great to have your help on these ones.

**Comment by jamiefolsom** [comment]
Hi @jsravel4,

Our testing process results in a new github issue being created on the associated github code repository in any case where there's a problem identified. This makes it easy for us to track progress on correcting those issues.

The report you mention will be a list of issues; I would be glad to deliver that to you as a single document if you would like, but if you have no objection, this process (of creating one discrete ticket per issue) will facilitate our collective effort on correcting any straggling problems. 

In the meantime, you can turn off email notifications for yourself, so that you don't get an email every time a new issue is opened. Just log into your github account, and go to Settings > Notifications (i.e: https://github.com/settings/notifications), and uncheck any notifications you don't want to receive.

Let me know if that makes sense to you, 

Thanks,

Jamie

**Comment by jamiefolsom** [comment]
Also, I have pointed our tester, Steve, to the correct repository to put issues regarding the website on, which is: https://github.com/hyperstudio/cfrp-craft. I am closing this issue as being on the wrong repo, and will reopen it on the correct one.
